#!/bin/bash
# Rename school + healthcare images to keyword-rich filenames
# and update all references in the .astro files

IMGDIR="/Users/christianneaengenheyster/.openclaw/workspace/projects/window-film-philadelphia/public/images"
SC="/Users/christianneaengenheyster/.openclaw/workspace/projects/window-film-philadelphia/src/pages/applications/schools-universities.astro"
HE="/Users/christianneaengenheyster/.openclaw/workspace/projects/window-film-philadelphia/src/pages/applications/healthcare.astro"

rename_and_replace() {
  local OLD="$1"
  local NEW="$2"
  local FILES="${@:3}"
  if [ -f "$IMGDIR/$OLD" ]; then
    mv "$IMGDIR/$OLD" "$IMGDIR/$NEW"
    echo "✅ $OLD → $NEW"
  else
    echo "⚠️  NOT FOUND: $OLD"
  fi
  for FILE in $FILES; do
    sed -i '' "s|$OLD|$NEW|g" "$FILE"
  done
}

echo "=== SCHOOLS ==="
rename_and_replace sc-hero.jpg                  school-window-film-philadelphia-hero.jpg                                    "$SC"
rename_and_replace sc-cta-bg.jpg                school-window-film-philadelphia-cta-background.jpg                         "$SC"
rename_and_replace sc-whatis.jpg                school-window-film-philadelphia-what-is-window-film.jpg                    "$SC"
rename_and_replace sc-why.jpg                   school-window-film-philadelphia-why-schools-need-film.jpg                  "$SC"
rename_and_replace sc-type-k12.jpg              k12-school-window-film-philadelphia-classroom.jpg                          "$SC"
rename_and_replace sc-type-university.jpg       university-window-film-philadelphia-glass-facade.jpg                       "$SC"
rename_and_replace sc-type-charter.jpg          charter-school-window-film-philadelphia-entry-glass.jpg                    "$SC"
rename_and_replace sc-type-childcare.jpg        childcare-center-uv-safety-window-film-philadelphia.jpg                    "$SC"
rename_and_replace sc-security.jpg              school-security-window-film-philadelphia-entry-glass.jpg                   "$SC"
rename_and_replace sc-uv.jpg                    school-uv-protection-window-film-philadelphia-classroom.jpg                "$SC"
rename_and_replace sc-glare.jpg                 glare-reduction-window-film-school-smartboard-philadelphia.jpg             "$SC"
rename_and_replace sc-energy.jpg                energy-saving-school-window-film-philadelphia-educational-facility.jpg     "$SC"
rename_and_replace sc-slider-safety.jpg         school-safety-window-film-philadelphia-entry-glass-slider.jpg              "$SC"
rename_and_replace sc-slider-uv.jpg             school-uv-window-film-philadelphia-classroom-windows-slider.jpg            "$SC"
rename_and_replace sc-slider-glare.jpg          glare-control-window-film-school-smartboard-philadelphia-slider.jpg        "$SC"
rename_and_replace sc-slider-energy.jpg         energy-efficiency-window-film-philadelphia-university-slider.jpg           "$SC"
rename_and_replace sc-slider-decorative.jpg     decorative-frosted-privacy-film-school-office-philadelphia-slider.jpg      "$SC"
rename_and_replace sc-slider-security.jpg       anti-graffiti-window-film-school-glass-philadelphia-slider.jpg             "$SC"
rename_and_replace sc-case-study.jpg            school-window-film-case-study-west-philadelphia-k12.jpg                    "$SC"
rename_and_replace sc-gallery-1.jpg             school-window-film-philadelphia-natural-light-classroom.jpg                "$SC"
rename_and_replace sc-gallery-2.jpg             university-safety-window-film-philadelphia-glass-entrance.jpg              "$SC"
rename_and_replace sc-gallery-3.jpg             school-privacy-window-film-philadelphia-counselor-office.jpg               "$SC"
rename_and_replace sc-gallery-4.jpg             school-glare-reduction-film-computer-lab-philadelphia.jpg                  "$SC"
rename_and_replace sc-gallery-5.jpg             school-uv-window-film-philadelphia-library.jpg                             "$SC"
rename_and_replace sc-gallery-6.jpg             school-security-film-main-entrance-philadelphia.jpg                        "$SC"
rename_and_replace sc-gallery-7.jpg             university-campus-window-film-philadelphia-aerial.jpg                      "$SC"
rename_and_replace sc-resources.jpg             school-window-film-specifications-philadelphia.jpg                         "$SC"
rename_and_replace sc-testimonial-1.jpg         school-window-film-philadelphia-administrator-testimonial.jpg              "$SC"
rename_and_replace sc-testimonial-2.jpg         school-window-film-philadelphia-facilities-director-testimonial.jpg        "$SC"
rename_and_replace sc-testimonial-3.jpg         university-window-film-philadelphia-facilities-manager-testimonial.jpg     "$SC"

echo ""
echo "=== HEALTHCARE ==="
rename_and_replace he-hero.jpg                  hospital-window-film-philadelphia-hero.jpg                                  "$HE"
rename_and_replace he-cta-bg.jpg                hospital-window-film-philadelphia-cta-background.jpg                       "$HE"
rename_and_replace he-whatis.jpg                hospital-window-film-philadelphia-what-is-film.jpg                         "$HE"
rename_and_replace he-why.jpg                   hospital-window-film-philadelphia-why-facilities-need-film.jpg             "$HE"
rename_and_replace he-type-clinic.jpg           outpatient-clinic-window-film-philadelphia.jpg                             "$HE"
rename_and_replace he-type-surgical.jpg         surgical-center-safety-window-film-philadelphia.jpg                        "$HE"
rename_and_replace he-type-hospital.jpg         hospital-campus-window-film-philadelphia.jpg                               "$HE"
rename_and_replace he-type-dental.jpg           dental-office-window-film-philadelphia.jpg                                 "$HE"
rename_and_replace he-uv.jpg                    uv-protection-window-film-hospital-patient-room-philadelphia.jpg           "$HE"
rename_and_replace he-energy.jpg                energy-saving-hospital-window-film-philadelphia-facility.jpg               "$HE"
rename_and_replace he-privacy.jpg               privacy-window-film-medical-consultation-room-philadelphia.jpg             "$HE"
rename_and_replace he-security.jpg              security-window-film-hospital-pharmacy-philadelphia.jpg                    "$HE"
rename_and_replace he-slider-uv.jpg             hospital-uv-window-film-philadelphia-patient-room-slider.jpg               "$HE"
rename_and_replace he-slider-energy.jpg         hospital-energy-window-film-philadelphia-facility-slider.jpg               "$HE"
rename_and_replace he-slider-glare.jpg          hospital-glare-window-film-philadelphia-waiting-room-slider.jpg            "$HE"
rename_and_replace he-slider-privacy.jpg        hospital-privacy-window-film-philadelphia-consultation-slider.jpg          "$HE"
rename_and_replace he-slider-security.jpg       hospital-security-window-film-philadelphia-pharmacy-slider.jpg             "$HE"
rename_and_replace he-slider-decorative.jpg     decorative-window-film-medical-office-philadelphia-slider.jpg              "$HE"
rename_and_replace he-case-study.jpg            hospital-window-film-case-study-university-city-philadelphia.jpg           "$HE"
rename_and_replace he-gallery-1.jpg             hospital-patient-room-uv-protection-window-film-philadelphia.jpg           "$HE"
rename_and_replace he-gallery-2.jpg             clinic-waiting-room-privacy-window-film-philadelphia.jpg                   "$HE"
rename_and_replace he-gallery-3.jpg             hospital-corridor-natural-light-window-film-philadelphia.jpg               "$HE"
rename_and_replace he-gallery-4.jpg             medical-office-privacy-window-film-reception-philadelphia.jpg              "$HE"
rename_and_replace he-gallery-5.jpg             hospital-pharmacy-security-window-film-philadelphia.jpg                    "$HE"
rename_and_replace he-gallery-6.jpg             medical-building-safety-window-film-entrance-philadelphia.jpg              "$HE"
rename_and_replace he-gallery-7.jpg             philadelphia-hospital-campus-window-film-aerial.jpg                        "$HE"
rename_and_replace he-resources.jpg             hospital-window-film-specifications-case-studies-philadelphia.jpg          "$HE"
rename_and_replace he-testimonial-1.jpg         hospital-facilities-director-window-film-testimonial-philadelphia.jpg      "$HE"
rename_and_replace he-testimonial-2.jpg         healthcare-operations-manager-window-film-testimonial-philadelphia.jpg     "$HE"
rename_and_replace he-testimonial-3.jpg         medical-office-administrator-window-film-testimonial-philadelphia.jpg      "$HE"

echo ""
echo "Done."
